export const constants = {
  WelcomeTitle: 'WELCOME TO',
  WelcomeTitle2: 'COVID-ALERT',
  Started: 'GET STARTED',
  SignIn: 'Sign In',
  ForgotPassword: 'Forgot password?',
  Hello: 'Hello,',
  name: 'name',
  Stay: 'STAY HOME',
  Prevention1: 'Take preventive measures',
  Prevention2: 'against possible infenction.',
  location: 'Location',
  symptoms: 'Symptoms',
  result: 'Result',
  code: 'Code QR',
  nombre: 'Nombre, ',
  what: 'what',
  symptomsYouHave: 'symptoms do you',
  have: 'have?',
  submit: 'Submit',
  DateOfTest: 'Date the test was done',
  DateOfResult: 'Result date',
  TypeOfTest: 'Type of test',
  TestResult: 'Test result',
  SymptomsDayTest: 'Did you have symptoms on the day of the test?',
  result: 'Test result',
  Historial: 'Historial',
  Title: 'Place:',
  area: 'Área:',
  lugar: 'Lugar:',
  sistomatico: 'Sintómaticos:',
  negativo: 'Covid-negativo:',
  positivo: 'Covid-Positivo:',
  done: 'Done!',
  successfully: 'Submited successfully',
  message: 'Your data has been submited successfully',
  ForgotPassword: 'Forgot your password?',
  MessagePassword: 'Enter your email to reset your password',
  send: 'Send',
};
